services:

  # PDF Service
  pdf_service:
    build:
      context: .
      dockerfile: pdf_service/Dockerfile
    container_name: pdf_service
    ports:
      - "8000:8000"
    volumes:
      - "./uploads:/app/uploads"
    environment:
      - STORAGE_DIR=/app/uploads
    networks:
      - backend-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # RAG Module
  rag_module:
    build:
      context: .
      dockerfile: rag_module/Dockerfile
    container_name: rag_module
    ports:
      - "8001:8001"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - PINECONE_INDEX=${PINECONE_INDEX:-vector}
      - CHUNK_SIZE=${CHUNK_SIZE:-1000}
      - CHUNK_OVERLAP=${CHUNK_OVERLAP:-200}
      - TOP_K=${TOP_K:-5}
      - EMBEDDING_MODEL=${EMBEDDING_MODEL:-text-embedding-3-small}
      - LLM_MODEL=${LLM_MODEL:-gpt-3.5-turbo}
      - MAX_TOKENS=${MAX_TOKENS:-1000}
      - TEMPERATURE=${TEMPERATURE:-0.7}
      - EMBEDDING_DIMENSION=${EMBEDDING_DIMENSION:-1536}
      - PINECONE_METRIC=${PINECONE_METRIC:-cosine}
      - PINECONE_CLOUD=${PINECONE_CLOUD:-aws}
      - PINECONE_REGION=${PINECONE_REGION:-us-east-1}
      - PDF_SERVICE_URL=http://pdf_service:8000
      - PDF_SERVICE_TIMEOUT=30.0
      - METRICS_LAMBDA_URL=${METRICS_LAMBDA_URL:-http://metrics_lambda:9000}
      - METRICS_TIMEOUT=30.0
    depends_on:
      - pdf_service
    networks:
      - backend-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  backend-network:
    driver: bridge
