[project]
name = "backend-recruitment-exercise"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.116.1",
    "pymupdf>=1.26.3",
    "python-multipart>=0.0.20",
    "uvicorn[standard]>=0.35.0",
]
